SCREEN_WIDTH = 1440
SCREEN_HEIGHT = 800
CARD_WIDTH = 80
CARD_HEIGHT = 120

PROFILE_EMOJIS = [
    r"UwU", r":D", r":^D", r"OwO", r">_<", r"^_^", r"T_T", r"¯\_(ツ)_/¯"
]

# Add near other constants
SAVE_BUTTON_X = SCREEN_WIDTH - 140
LOAD_BUTTON_X = SCREEN_WIDTH - 240
BUTTON_Y = 50
BUTTON_WIDTH = 80
BUTTON_HEIGHT = 30